### ISSUE TITLE
Get not the money what is showing

### ISSUE THREAD

**Issue by actus18** [GMNGjoy/FS25_ContractBoost#33] opened 2024-12-19 18:37 UTC
Hi,

i use your mod but if i finish a contract i dont get the money what is showing.

Example: showing 5000€ if i finish but i only get 1500€

**Comment by actus18** [comment] 2024-12-19 18:44
![Screenshot 2024-12-19 194155](https://github.com/user-attachments/assets/5fa6eaef-fffb-4999-887f-28890dc5b363)
![Screenshot 2024-12-19 194427](https://github.com/user-attachments/assets/4aec6d1b-8f70-48a7-a2cf-a09abe17ece6)

**Comment by GMNGjoy** [comment] 2024-12-19 18:54
The screenshots which did not somehow come through with this ticket showed a mission that had a reward of $4,401 and a resulted profit of resulting profit of $3,881... which is close, but obviously not correct - but there was no screenshot of right before accepting the contract - which would also show if there was borrowed equipment.

- WHAT VERSION ARE YOU USING?
- was there borrowed equipment?
- was the `enableCollectingBalesFromMissions` flag turned on or off? 
   - if it was on, did you take the bales and do something with them before collecting the contract?

**Comment by actus18** [comment] 2024-12-19 19:01
I made a another mission one minute ago.
Showing was 7400 i rent the equipt for 759 but i only got 1800

**Comment by GMNGjoy** [comment] 2024-12-19 19:07
> I made a another mission one minute ago. Showing was 7400 i rent the equipt for 759 but i only got 1800 Mission was a mow

I'm sorry that you're experiencing this issue,

- what version of the mod? 
- is this on a server, or single player?
- borrowed equipment? 
- for the mowing mission - are you using the mod to "steal" the grass?
- for the reward - are you getting a different amount put into your account than the amount that is published on the screen (either in the complete contract screen, or what shows up in the alert; the green text top right under your account)

I need more information before being able to debug or reproduce.

**Comment by actus18** [comment] 2024-12-19 19:36
![Screenshot 2024-12-19 203538](https://github.com/user-attachments/assets/59b45f2d-6c7f-49a2-9e7d-7cab7081f582)
![Screenshot 2024-12-19 203548](https://github.com/user-attachments/assets/8d2a6784-ad64-4a68-b08e-7c38167b206a)

**Comment by actus18** [comment] 2024-12-19 19:37
what version of the mod?
the newest

is this on a server, or single player?
Server

borrowed equipment?
no

are you customizing (via the mod) the overall rewardFactor or are you customizing individual contracts by type?
the overall is on 1.5

for the mowing mission - are you using the mod to "steal" the grass?
no

for the reward - are you getting a different amount put into your account than the amount that is published on the screen (either in the complete contract screen, or what shows up in the alert; the green text top right under your account)
no

**Comment by GMNGjoy** [comment] 2024-12-27 02:12
duplicate of #23; This is related to dedicated servers, and the incorrect sync of settings between server and client.

**Closed by GMNGjoy** 2024-12-27 02:12 UTC
