### ISSUE TITLE
Wood Transport Missions

### ISSUE THREAD

**Issue by Kitekater** [GMNGjoy/FS25_ContractBoost#37] opened 2024-12-21 21:49 UTC
Hello,
unfortunately it seems the increase in value does not work for wood transport. Neither SP nor MP

Greetings
Marc

**Comment by GMNGjoy** [comment] 2024-12-22 09:34
> Hello,
> 
> unfortunately it seems the increase in value does not work for wood transport. Neither SP nor MP
> 
> 
> 
> Greetings
> 
> Marc

Marc - it looks like you've opened, closed and opened this same ticket - is this still an issue for you in SP with the latest version? 

MP is not currently showing / rewarding correctly (for all missions), but a fix for that part of the issue is in progress.

**Comment by Kitekater** [comment] 2024-12-22 10:43
Hi,

sorry yesterday i opend a bug report. So i closed it and opend a "normal" issue.
I had same payment, listed with the savegame of the MP in my SP.
But i havent tested it yet, if the payment is different to the shown money in contract list.
Its right that i dont have to "tune" the file in the modsettings for getting other payment. Its all in the menu now?

**Comment by GMNGjoy** [comment] 2024-12-27 02:12
duplicate of #23; This is related to dedicated servers, and the incorrect sync of settings between server and client.

**Closed by GMNGjoy** 2024-12-27 02:12 UTC
